### ISSUE TITLE
Compressed code count

### ISSUE THREAD

**Issue by speedstyle** [Soaku/Pepe#16]
You should put a second compressed byte count as minimum/4, since each character can be encoded with two bits (to specify `r` or `e` and capital or lowercase).

**Comment by Soaku** [comment]
Thanks for your issue! This is possible but only if two-bit-per-character compression gets implemented too, otherwise it doesn't serve much use now. 

Also, once Pepe v2.0 gets released compression will not be needed at all – code will be stored on paste.gg, but this requires jkcclemens/paste#118 to be implemented first.
